import { Bell, Check, ChevronRight, Home, Map, Plus, Search, School as SchoolIcon, UserRound, X } from "lucide-react";

const tabs = [{label:"Home",icon:Home},{label:"Schools",icon:SchoolIcon,active:true},{label:"Roadmap",icon:Map},{label:"Alerts",icon:Bell},{label:"Profile",icon:UserRound}];
function TabBar() { return <nav className="fixed bottom-0 left-0 right-0 z-20 flex h-[76px] items-center justify-around border-t-2 border-[#171744]/10 bg-[#fffaf0]/95 px-2 backdrop-blur-md">{tabs.map(({label,icon:Icon,active})=><button key={label} className={`flex w-16 flex-col items-center gap-1 text-[10px] font-black ${active?"text-[#ff4d67]":"text-[#77748a]"}`}><span className={`flex h-9 w-11 items-center justify-center rounded-2xl ${active?"bg-[#ff4d67] text-white shadow-[3px_3px_0_#171744]":""}`}><Icon size={19} strokeWidth={2.5}/></span>{label}</button>)}</nav> }
export function Schools() {
 return <main className="min-h-screen w-full bg-[#fffaf0] pb-24 font-['Nunito',sans-serif] text-[#171744]"><header className="bg-[#b7a5ff] px-6 pb-6 pt-10"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[2px] text-[#171744]/60">Your destination</p><h1 className="mt-1 text-[32px] font-black leading-none tracking-[-1.5px]">Find your fit.</h1></div><div className="flex h-12 w-12 items-center justify-center rounded-[18px] bg-[#ffbf3f] font-black shadow-[3px_3px_0_#171744]">68%</div></div><div className="mt-5 flex items-center gap-3 rounded-[18px] border-2 border-[#171744]/20 bg-white px-4 py-3"><Search size={20}/><span className="flex-1 text-sm font-bold text-[#77748a]">Search universities</span><X size={16} className="text-[#77748a]"/></div></header>
 <section className="px-6 pt-6"><div className="flex gap-2 overflow-x-auto pb-1">{["All","CC","UC","CSU"].map((f,i)=><button key={f} className={`rounded-full px-5 py-2 text-xs font-black ${i===0?"bg-[#ff4d67] text-white shadow-[2px_2px_0_#171744]":"border-2 border-[#171744]/10 bg-white"}`}>{f}</button>)}</div><div className="mt-6 rounded-[22px] border-2 border-[#171744]/10 bg-[#a4e85d] p-4"><p className="text-[11px] font-black uppercase tracking-[1.5px]">Current campus</p><div className="mt-2 flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#171744] text-sm font-black text-white">DA</div><div><p className="font-black">De Anza College</p><p className="text-xs font-bold opacity-70">Cupertino, CA · Community College</p></div><Check className="ml-auto" size={21} strokeWidth={3}/></div></div>
 <div className="mt-7 flex items-center justify-between"><h2 className="text-xl font-black">Your targets</h2><button className="text-xs font-black text-[#ff4d67]"><Plus className="inline" size={15}/> Add school</button></div><div className="mt-3 space-y-3">{[["UC","UC Berkeley","Computer Science B.S.","#ffbf3f"],["U","UCLA","Cognitive Science","#ff4d67"]].map(([mark,school,degree,color])=><div key={school} className="rounded-[20px] border-2 border-[#171744]/10 bg-white p-4"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl text-lg font-black" style={{backgroundColor:color}}>{mark}</div><div className="flex-1"><p className="font-black">{school}</p><p className="text-xs font-bold text-[#77748a]">{degree}</p></div><ChevronRight size={20}/></div><button className="mt-3 w-full rounded-xl bg-[#171744] py-2.5 text-xs font-black text-white">View transfer requirements</button></div>)}</div>
 <h2 className="mb-3 mt-7 text-xl font-black">More possibilities</h2><div className="space-y-3">{[["UCSD","UC San Diego","Data Science","#b7a5ff"],["SJSU","San Jose State","Software Engineering","#a4e85d"]].map(([mark,school,degree,color])=><div key={school} className="flex items-center gap-3 rounded-[19px] border-2 border-[#171744]/10 bg-white p-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl text-[11px] font-black" style={{backgroundColor:color}}>{mark}</div><div className="flex-1"><p className="text-sm font-black">{school}</p><p className="text-xs font-bold text-[#77748a]">{degree}</p></div><button className="rounded-xl border-2 border-[#171744]/15 p-2"><Plus size={16}/></button></div>)}</div></section><TabBar/></main>;
}