import { Bookmark, Check, ChevronRight, MapPin, Search, SlidersHorizontal } from "lucide-react";
import { ArrowButton, SectionLabel, Shell } from "./_shared";

const targets = [["UC Berkeley","Computer Science B.S.","Berkeley, CA"],["UCLA","Cognitive Science","Los Angeles, CA"]];
export function Schools() {
  return <Shell active="Schools"><header className="px-5 pb-5 pt-7"><div className="flex items-center justify-between"><div><p className="text-[11px] font-extrabold uppercase tracking-[.15em] text-[#9A817D]">Your destinations</p><h1 className="mt-1 font-serif text-[32px] tracking-[-.04em]" style={{fontFamily:"Georgia, serif"}}>Find your next place.</h1></div><button onClick={()=>{}} className="rounded-full bg-[#EDE2EB] p-3 text-[#6F4C68]"><SlidersHorizontal size={18}/></button></div><div className="mt-5 flex items-center gap-3 rounded-2xl border border-[#E2D9D0] bg-[#FBF9F5] px-4 py-3 text-[#92918B]"><Search size={18}/><input className="w-full bg-transparent text-[13px] font-bold outline-none placeholder:text-[#AAA69F]" placeholder="Search schools or majors" /></div></header>
  <div className="flex gap-2 overflow-x-auto px-5 pb-6">{["All","CC","UC","CSU"].map((x,i)=><button onClick={()=>{}} key={x} className={`rounded-full px-4 py-2 text-[12px] font-extrabold ${i===0?"bg-[#6F4C68] text-[#FFF8F4]":"border border-[#DED4CC] bg-[#FBF9F5] text-[#777C7B]"}`}>{x}</button>)}</div>
  <section className="mx-5 mb-6 rounded-2xl border border-[#E7DED4] bg-[#F1EAE2] p-4"><div className="flex items-start gap-3"><MapPin size={18} className="mt-0.5 text-[#C86B58]"/><div><SectionLabel>Your community college</SectionLabel><p className="text-[16px] font-black">De Anza College</p><p className="mt-1 text-[11px] font-semibold text-[#7F8583]">Cupertino, California · 42 units completed</p></div></div></section>
  <section className="px-5"><SectionLabel>Selected targets · 2</SectionLabel><div className="space-y-3">{targets.map(([school,major,place])=><div className="rounded-2xl border border-[#DCCBD9] bg-[#FBF9F5] p-4" key={school}><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EDE2EB] text-[#6F4C68]"><Bookmark size={18} fill="currentColor"/></div><div className="flex-1"><p className="text-[15px] font-black">{school}</p><p className="mt-0.5 text-[12px] font-bold text-[#6F4C68]">{major}</p><p className="mt-1 text-[11px] font-semibold text-[#969792]">{place}</p></div><Check size={17} className="text-[#547055]"/></div><div className="mt-4 border-t border-[#EEE6DE] pt-3"><ArrowButton>View transfer requirements</ArrowButton></div></div>)}</div></section>
  <section className="px-5 pb-4 pt-7"><SectionLabel>Worth a look</SectionLabel><div className="divide-y divide-[#E9E0D7] rounded-2xl border border-[#E7DED4] bg-[#FBF9F5] px-4">{[["UC San Diego","Data Science B.S.","La Jolla, CA"],["San Jose State","Computer Science B.S.","San Jose, CA"]].map(([s,m,p])=><button onClick={()=>{}} key={s} className="flex w-full items-center gap-3 py-4 text-left"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#F1EAE2] text-[#C86B58]"><Bookmark size={16}/></div><div className="flex-1"><p className="text-[13px] font-extrabold">{s}</p><p className="mt-1 text-[11px] font-semibold text-[#8C908D]">{m} · {p}</p></div><ChevronRight size={16} className="text-[#B8B0A8]"/></button>)}</div></section>
  </Shell>;
}