// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/redesign-bold/Home.tsx": () => import("../components/mockups/redesign-bold/Home.tsx"),
  "./components/mockups/redesign-bold/Roadmap.tsx": () => import("../components/mockups/redesign-bold/Roadmap.tsx"),
  "./components/mockups/redesign-bold/Schools.tsx": () => import("../components/mockups/redesign-bold/Schools.tsx"),
  "./components/mockups/redesign-dark/Home.tsx": () => import("../components/mockups/redesign-dark/Home.tsx"),
  "./components/mockups/redesign-dark/Roadmap.tsx": () => import("../components/mockups/redesign-dark/Roadmap.tsx"),
  "./components/mockups/redesign-dark/Schools.tsx": () => import("../components/mockups/redesign-dark/Schools.tsx"),
  "./components/mockups/redesign-editorial/Home.tsx": () => import("../components/mockups/redesign-editorial/Home.tsx"),
  "./components/mockups/redesign-editorial/Roadmap.tsx": () => import("../components/mockups/redesign-editorial/Roadmap.tsx"),
  "./components/mockups/redesign-editorial/Schools.tsx": () => import("../components/mockups/redesign-editorial/Schools.tsx")
};
